spring.application.name=demo-kafka-oracle
server.port=8081

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=Dev
spring.datasource.password=Dev123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=ordenes-group
spring.kafka.consumer.auto-offset-reset=earliest

topic.ordenes=ordenes