CREATE OR REPLACE PROCEDURE COREPRESTAMOS.SPCPNORMALIZETOPIC00015(
   PA_MESSAGEJN  IN  CLOB,
   PA_CODERESULT OUT NUMBER,
   PA_MESSAGE    OUT VARCHAR2
) AS
/*************************************************************
 * PROYECTO: NCP
 * DESCRIPCION: GESTOR TOPICOS SOCIOS-COMERCIALES-ADD
 * PARAMETROS DE ENTRADA: PARAMETROS INDIVIDUALES
 * PARAMETROS DE SALIDA: EXITO / ERROR
 * VALOR DE RETORNO: PA_CODERESULT, PA_MESSAGE
 * PARAMETROS DE ENTRADA-SALIDA: ---
 * PRECONDICIONES: NINGUNA
 * CREADOR: GERARDO FABIAN
 * FECHA DE CREACION: 27/11/2025
 * MODIFICO:
 * FECHA DE MODIFICACION:--
 * MODIFICACION: --
 * VERSION: 1.0.1
*************************************************************/
   CSL_0                CONSTANT SIMPLE_INTEGER := 0;
   CSL_1                CONSTANT SIMPLE_INTEGER := 1;
   CSL_ARROW_INDICATOR  CONSTANT VARCHAR2(5)    := '->';
   CSL_500                    CONSTANT SIMPLE_INTEGER := 500;

   CSL_MSJEXITO         CONSTANT VARCHAR2(100)  := 'Exito al ejecutar SPCPNORMALIZETOPIC00015';
   CSL_MSJ_SIN          CONSTANT VARCHAR2(150)  := 'Error con JSON de entrada, favor de verificar';

   CSL_AGENTE           CONSTANT VARCHAR2(30)   := 'agente';
   CSL_SUBSIDIARIA      CONSTANT VARCHAR2(30)   := 'subsidiaria';
   CSL_SUCURSAL         CONSTANT VARCHAR2(30)   := 'sucursal';
   CSL_MEDIOSUCURSAL    CONSTANT VARCHAR2(30)   := 'medioContacto';
   CSL_ID               CONSTANT VARCHAR2(30)   := 'id';
   CSL_DESCRIPCION      CONSTANT VARCHAR2(30)   := 'descripcion';

   OBJ_DATA_JSON              JSON_OBJECT_T;
   OBJ_OPERACION              JSON_OBJECT_T;
   OBJ_SOLICITUD              JSON_OBJECT_T;
   OBJ_PLATAFORMA             JSON_OBJECT_T;
   OBJ_TIPO                   JSON_OBJECT_T;
   OBJ_DETALLE_EVENTO         JSON_OBJECT_T;
   OBJ_SOCIO_COMERCIAL        JSON_OBJECT_T;
   OBJ_AGENTE                 JSON_OBJECT_T;
   OBJ_SUBSIDIARIA            JSON_OBJECT_T;
   OBJ_SUCURSAL               JSON_OBJECT_T;
   OBJ_MEDIO_CONTACTO         JSON_OBJECT_T;
   OBJ_PAIS                   JSON_OBJECT_T;

   VL_FIIDPERSONA             RCREDITO.TACPORGSOLSCOMERCIAL.FIIDPERSONA%TYPE;
   VL_FIIDPLATAFORMA          RCREDITO.TACPORGSOLSCOMERCIAL.FIIDPLATAFORMA%TYPE;
   VL_FIIDTIPOSOLICITUD       RCREDITO.TACPORGSOLSCOMERCIAL.FIIDTIPOSOLICITUD%TYPE;
   VL_FICONSECSOLI            RCREDITO.TACPORGSOLSCOMERCIAL.FICONSECUTIVOSOLICITUD%TYPE;
   VL_FIAGENTSOCIOCOMER       RCREDITO.TACPORGSOLSCOMERCIAL.FIAGENTESOCIOCOMERCIAL%TYPE;
   VL_FCAGENTSOCIOCOMER       RCREDITO.TACPORGSOLSCOMERCIAL.FCAGENTESOCIOCOMERCIAL%TYPE;
   VL_FIIDSUBSIDIARIA         RCREDITO.TACPORGSOLSCOMERCIAL.FIIDSUBSIDIARIA%TYPE;
   VL_FCSUBSIDIARIA           RCREDITO.TACPORGSOLSCOMERCIAL.FCSUBSIDIARIA%TYPE;
   VL_FIIDSUCURSAL            RCREDITO.TACPORGSOLSCOMERCIAL.FIIDSUCURSAL%TYPE;
   VL_FCSUCURSAL              RCREDITO.TACPORGSOLSCOMERCIAL.FCSUCURSAL%TYPE;
   VL_FIMEDIOCONTACTO         RCREDITO.TACPORGSOLSCOMERCIAL.FIMEDIOCONTACTO%TYPE;
   VL_FCMEDIOCONTACTO         RCREDITO.TACPORGSOLSCOMERCIAL.FCMEDIOCONTACTO%TYPE;
   VL_FIIDCADENCOMERCIA       RCREDITO.TACPORGSOLSCOMERCIAL.FIIDCADENACOMERCIAL%TYPE;
   VL_FIIDGIRO                RCREDITO.TACPORGSOLSCOMERCIAL.FIIDGIRO%TYPE;
   VL_FINUMEROECONOMICO       RCREDITO.TACPORGSOLSCOMERCIAL.FINUMEROECONOMICO%TYPE;
   VL_FIIDPAIS                RCREDITO.TACPORGSOLSCOMERCIAL.FIIDPAIS%TYPE;
   VL_CODERESULT              NUMBER (1,0);
   VL_MESSAGE                 VARCHAR2(500);

   EXC_SPFAILURE        EXCEPTION;
   EXC_JSON_SYNTAX_ERR  EXCEPTION;
   PRAGMA EXCEPTION_INIT (EXC_JSON_SYNTAX_ERR, -40441);

BEGIN
    OBJ_DATA_JSON := JSON_OBJECT_T(PA_MESSAGEJN);
    OBJ_OPERACION := OBJ_DATA_JSON.GET_OBJECT('operacion');
    VL_FIIDPERSONA := OBJ_OPERACION.GET_STRING('idProspecto');

    OBJ_SOLICITUD := OBJ_OPERACION.GET_OBJECT('solicitud');
    VL_FICONSECSOLI := OBJ_SOLICITUD.GET_NUMBER('folio');

    OBJ_PLATAFORMA := OBJ_SOLICITUD.GET_OBJECT('plataforma');
    OBJ_TIPO       := OBJ_SOLICITUD.GET_OBJECT('tipo');
    VL_FIIDPLATAFORMA    := OBJ_PLATAFORMA.GET_NUMBER(CSL_ID);
    VL_FIIDTIPOSOLICITUD := OBJ_TIPO.GET_NUMBER(CSL_ID);

    OBJ_DETALLE_EVENTO := OBJ_OPERACION.GET_OBJECT('detalleEvento');
    OBJ_PAIS           := OBJ_DETALLE_EVENTO.GET_OBJECT('pais');
    VL_FIIDPAIS        := OBJ_PAIS.GET_NUMBER(CSL_ID);

    OBJ_SOCIO_COMERCIAL := OBJ_OPERACION.GET_OBJECT('socioComercial');

    IF OBJ_SOCIO_COMERCIAL.HAS(CSL_AGENTE) AND NOT OBJ_SOCIO_COMERCIAL.GET(CSL_AGENTE).IS_NULL THEN
        OBJ_AGENTE := OBJ_SOCIO_COMERCIAL.GET_OBJECT(CSL_AGENTE);
        VL_FIAGENTSOCIOCOMER := OBJ_AGENTE.GET_NUMBER(CSL_ID);
        VL_FCAGENTSOCIOCOMER := OBJ_AGENTE.GET_STRING(CSL_DESCRIPCION);
    ELSE
        VL_FIAGENTSOCIOCOMER := NULL;
        VL_FCAGENTSOCIOCOMER := NULL;
    END IF;

    IF OBJ_SOCIO_COMERCIAL.HAS(CSL_SUBSIDIARIA) AND NOT OBJ_SOCIO_COMERCIAL.GET(CSL_SUBSIDIARIA).IS_NULL THEN
        OBJ_SUBSIDIARIA   := OBJ_SOCIO_COMERCIAL.GET_OBJECT(CSL_SUBSIDIARIA);
        VL_FIIDSUBSIDIARIA := OBJ_SUBSIDIARIA.GET_NUMBER(CSL_ID);
        VL_FCSUBSIDIARIA   := OBJ_SUBSIDIARIA.GET_STRING(CSL_DESCRIPCION);
    ELSE
        VL_FIIDSUBSIDIARIA := NULL;
        VL_FCSUBSIDIARIA   := NULL;
    END IF;

    IF OBJ_SOCIO_COMERCIAL.HAS(CSL_SUCURSAL) AND NOT OBJ_SOCIO_COMERCIAL.GET(CSL_SUCURSAL).IS_NULL THEN
        OBJ_SUCURSAL    := OBJ_SOCIO_COMERCIAL.GET_OBJECT(CSL_SUCURSAL);
        VL_FIIDSUCURSAL := OBJ_SUCURSAL.GET_NUMBER(CSL_ID);
        VL_FCSUCURSAL   := OBJ_SUCURSAL.GET_STRING(CSL_DESCRIPCION);
    ELSE
        VL_FIIDSUCURSAL := NULL;
        VL_FCSUCURSAL   := NULL;
    END IF;

    IF OBJ_SOCIO_COMERCIAL.HAS(CSL_MEDIOSUCURSAL) AND NOT OBJ_SOCIO_COMERCIAL.GET(CSL_MEDIOSUCURSAL).IS_NULL THEN
        OBJ_MEDIO_CONTACTO := OBJ_SOCIO_COMERCIAL.GET_OBJECT(CSL_MEDIOSUCURSAL);
        VL_FIMEDIOCONTACTO := OBJ_MEDIO_CONTACTO.GET_NUMBER(CSL_ID);
        VL_FCMEDIOCONTACTO := OBJ_MEDIO_CONTACTO.GET_STRING(CSL_DESCRIPCION);
    ELSE
        VL_FIMEDIOCONTACTO := NULL;
        VL_FCMEDIOCONTACTO := NULL;
    END IF;

    VL_FIIDCADENCOMERCIA := OBJ_SOCIO_COMERCIAL.GET_NUMBER('idMarcaComercial');
    VL_FIIDGIRO            := OBJ_SOCIO_COMERCIAL.GET_NUMBER('idGiro');
    VL_FINUMEROECONOMICO   := OBJ_SOCIO_COMERCIAL.GET_NUMBER('numeroEconomico');

    COREPRESTAMOS.SPCPORGSOLSCOMERCIAL(
        PA_FIIDPERSONA             => VL_FIIDPERSONA,
        PA_FIIDPLATAFORMA          => VL_FIIDPLATAFORMA,
        PA_FIIDTIPOSOLICITUD       => VL_FIIDTIPOSOLICITUD,
        PA_FICONSECSOLI            => VL_FICONSECSOLI,
        PA_FIAGENTSOCIOCOMER       => VL_FIAGENTSOCIOCOMER,
        PA_FCAGENTSOCIOCOMER       => VL_FCAGENTSOCIOCOMER,
        PA_FIIDSUBSIDIARIA         => VL_FIIDSUBSIDIARIA,
        PA_FCSUBSIDIARIA           => VL_FCSUBSIDIARIA,
        PA_FIIDSUCURSAL            => VL_FIIDSUCURSAL,
        PA_FCSUCURSAL              => VL_FCSUCURSAL,
        PA_FIMEDIOCONTACTO         => VL_FIMEDIOCONTACTO,
        PA_FCMEDIOCONTACTO         => VL_FCMEDIOCONTACTO,
        PA_FIIDCADENCOMERCIA       => VL_FIIDCADENCOMERCIA,
        PA_FIIDGIRO                => VL_FIIDGIRO,
        PA_FINUMEROECONOMICO       => VL_FINUMEROECONOMICO,
        PA_FIIDPAIS                => VL_FIIDPAIS,
        PA_CODERESULT              => VL_CODERESULT,
        PA_MESSAGE                 => VL_MESSAGE
    );

    IF VL_CODERESULT != CSL_0 THEN
        RAISE EXC_SPFAILURE;
    END IF;

    PA_CODERESULT := CSL_0;
    PA_MESSAGE    := CSL_MSJEXITO;

    COMMIT;
EXCEPTION
    WHEN EXC_JSON_SYNTAX_ERR THEN
      ROLLBACK;
      PA_CODERESULT := CSL_1;
      PA_MESSAGE    := CSL_MSJ_SIN;

    WHEN EXC_SPFAILURE THEN
      ROLLBACK;
      PA_CODERESULT := CSL_1;
      PA_MESSAGE := VL_MESSAGE;

   WHEN OTHERS THEN
      ROLLBACK;
      PA_CODERESULT := CSL_1;
      PA_MESSAGE := SUBSTR (SQLCODE ||
                            CSL_ARROW_INDICATOR ||
                            SQLERRM ||
                            CSL_ARROW_INDICATOR ||
                            DBMS_UTILITY.FORMAT_ERROR_STACK ||
                            CSL_ARROW_INDICATOR ||
                            DBMS_UTILITY.FORMAT_ERROR_BACKTRACE ,CSL_1 ,CSL_500);

END SPCPNORMALIZETOPIC00015;