CREATE OR REPLACE PROCEDURE SPINGESTALINEAGESTORACP(
    PA_IDPAIS           IN NUMBER,
    PA_IDCANAL          IN NUMBER,
    PA_IDSUCURSAL       IN NUMBER,
    PA_IDFOLIO          IN NUMBER,
    PA_STSID_EXTERNO    IN NUMBER,
    PA_GESTPAISID       IN NUMBER,
    PA_GESTCANALID      IN NUMBER,
    PA_GESTSUCURSALID   IN NUMBER
)
IS
    VL_FINGCIOID NUMBER(5, 0);
    VL_FINOTIENDA NUMBER(5, 0);
    VL_FICTEID NUMBER(10, 0);
    VL_FIDIGITOVER NUMBER(5, 0);
BEGIN
    SELECT FINGCIOID, FINOTIENDA, FICTEID, FIDIGITOVER
      INTO VL_FINGCIOID, VL_FINOTIENDA, VL_FICTEID, VL_FIDIGITOVER
      FROM (
        SELECT FINGCIOID, FINOTIENDA, FICTEID, FIDIGITOVER
          FROM RCREDITO.CENCLIENTETIENDA
         WHERE FIPAIS = PA_IDPAIS
           AND FICANAL = PA_IDCANAL
           AND FISUCURSAL = PA_IDSUCURSAL
           AND FIFOLIO = PA_IDFOLIO
         ORDER BY FDFECHA DESC
    )
     WHERE ROWNUM = 1;

    UPDATE RCREDITO.CENLINEADECREDITO
       SET FISTATUS = PA_STSID_EXTERNO,
           FINGCIOID = VL_FINGCIOID,
           FINOTIENDA = VL_FINOTIENDA,
           FICTEID = VL_FICTEID,
           FIDIGITOVER = VL_FIDIGITOVER,
           FDFECHAACT = SYSDATE
     WHERE FIPAIS = PA_IDPAIS
       AND FICANAL = PA_IDCANAL
       AND FISUCURSAL = PA_IDSUCURSAL
       AND FIFOLIO = PA_IDFOLIO;

    IF SQL%ROWCOUNT = 0 THEN
        INSERT INTO RCREDITO.CENLINEADECREDITO (
            FIPAIS,
            FICANAL,
            FISUCURSAL,
            FIFOLIO,
            FIPAISGESTOR,
            FICANALGESTOR,
            FISUCURSALGESTORA,
            FISTATUS,
            FDFECHAALTA,
            FDFECHAACT,
            FINGCIOID,
            FINOTIENDA,
            FICTEID,
            FIDIGITOVER,
            FISTSCU
        )
        VALUES (
            PA_IDPAIS,
            PA_IDCANAL,
            PA_IDSUCURSAL,
            PA_IDFOLIO,
            PA_GESTPAISID,
            PA_GESTCANALID,
            PA_GESTSUCURSALID,
            PA_STSID_EXTERNO,
            SYSDATE,
            SYSDATE,
            VL_FINGCIOID,
            VL_FINOTIENDA,
            VL_FICTEID,
            VL_FIDIGITOVER,
            0
        );
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20504, 'NOT_FOUND');
    WHEN OTHERS THEN
        IF SQLCODE BETWEEN -20999 AND -20000 THEN
            RAISE;
        END IF;

        RAISE_APPLICATION_ERROR(-20510, SUBSTR(SQLERRM, 1, 200));
END SPINGESTALINEAGESTORACP;
/