-- =====================================================
-- HR EXTENDIDO - MODELO EMPRESARIAL ROBUSTO
-- =====================================================

-- =========================
-- REGIONS
-- =========================
CREATE TABLE regions (
    region_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code          VARCHAR2(10) UNIQUE,
    region_name          VARCHAR2(100) NOT NULL,
    regional_director    VARCHAR2(100),
    timezone             VARCHAR2(50),
    currency_code        VARCHAR2(3),
    active_flag          CHAR(1) DEFAULT 'Y' CHECK (active_flag IN ('Y','N')),
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP,
    created_by           VARCHAR2(50),
    updated_at           TIMESTAMP,
    updated_by           VARCHAR2(50)
);

-- =========================
-- COUNTRIES
-- =========================
CREATE TABLE countries (
    country_id           CHAR(2) PRIMARY KEY,
    iso3_code            CHAR(3),
    country_name         VARCHAR2(150) NOT NULL,
    capital_city         VARCHAR2(100),
    population           NUMBER,
    area_km2             NUMBER,
    language_code        VARCHAR2(10),
    currency_code        VARCHAR2(3),
    tax_rate             NUMBER(5,2),
    labor_law_reference  VARCHAR2(200),
    region_id            NUMBER,
    active_flag          CHAR(1) DEFAULT 'Y' CHECK (active_flag IN ('Y','N')),
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP,
    created_by           VARCHAR2(50),
    updated_at           TIMESTAMP,
    updated_by           VARCHAR2(50),

    CONSTRAINT countries_region_fk
        FOREIGN KEY (region_id)
        REFERENCES regions(region_id)
);

-- =========================
-- LOCATIONS
-- =========================
CREATE TABLE locations (
    location_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_code        VARCHAR2(20) UNIQUE,
    street_address       VARCHAR2(200),
    building_number      VARCHAR2(20),
    floor_number         VARCHAR2(10),
    postal_code          VARCHAR2(20),
    city                 VARCHAR2(100) NOT NULL,
    state_province       VARCHAR2(100),
    country_id           CHAR(2),
    latitude             NUMBER(10,6),
    longitude            NUMBER(10,6),
    office_capacity      NUMBER,
    opened_date          DATE,
    closed_date          DATE,
    cost_center_code     VARCHAR2(20),
    lease_expiration     DATE,
    active_flag          CHAR(1) DEFAULT 'Y' CHECK (active_flag IN ('Y','N')),
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP,
    created_by           VARCHAR2(50),
    updated_at           TIMESTAMP,
    updated_by           VARCHAR2(50),

    CONSTRAINT locations_country_fk
        FOREIGN KEY (country_id)
        REFERENCES countries(country_id)
);

-- =========================
-- DEPARTMENTS
-- =========================
CREATE TABLE departments (
    department_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_code      VARCHAR2(20) UNIQUE,
    department_name      VARCHAR2(150) NOT NULL,
    description          VARCHAR2(500),
    manager_id           NUMBER,
    parent_department_id NUMBER,
    location_id          NUMBER,
    budget_amount        NUMBER(15,2),
    actual_spent         NUMBER(15,2),
    fiscal_year          NUMBER(4),
    headcount_limit      NUMBER,
    cost_center_code     VARCHAR2(30),
    strategic_flag       CHAR(1) CHECK (strategic_flag IN ('Y','N')),
    start_date           DATE,
    end_date             DATE,
    status               VARCHAR2(30),
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP,
    created_by           VARCHAR2(50),
    updated_at           TIMESTAMP,
    updated_by           VARCHAR2(50),

    CONSTRAINT dept_location_fk
        FOREIGN KEY (location_id)
        REFERENCES locations(location_id),

    CONSTRAINT dept_parent_fk
        FOREIGN KEY (parent_department_id)
        REFERENCES departments(department_id)
);

-- =========================
-- JOBS
-- =========================
CREATE TABLE jobs (
    job_id               VARCHAR2(20) PRIMARY KEY,
    job_code             VARCHAR2(20) UNIQUE,
    job_title            VARCHAR2(150) NOT NULL,
    job_description      VARCHAR2(1000),
    min_salary           NUMBER(15,2),
    max_salary           NUMBER(15,2),
    pay_grade            VARCHAR2(20),
    job_level            NUMBER,
    bonus_eligible_flag  CHAR(1) CHECK (bonus_eligible_flag IN ('Y','N')),
    remote_eligible_flag CHAR(1) CHECK (remote_eligible_flag IN ('Y','N')),
    travel_percentage    NUMBER(3),
    required_experience  NUMBER(3),
    required_degree      VARCHAR2(100),
    employment_type      VARCHAR2(50),
    union_applicable     CHAR(1) CHECK (union_applicable IN ('Y','N')),
    status               VARCHAR2(30),
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP,
    created_by           VARCHAR2(50),
    updated_at           TIMESTAMP,
    updated_by           VARCHAR2(50)
);

-- =========================
-- EMPLOYEES
-- =========================
CREATE TABLE employees (
    employee_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number      VARCHAR2(30) UNIQUE,
    first_name           VARCHAR2(100),
    middle_name          VARCHAR2(100),
    last_name            VARCHAR2(150) NOT NULL,
    gender               VARCHAR2(20),
    birth_date           DATE,
    national_id_number   VARCHAR2(50),
    marital_status       VARCHAR2(30),
    nationality          VARCHAR2(100),
    email                VARCHAR2(150) NOT NULL UNIQUE,
    personal_email       VARCHAR2(150),
    phone_number         VARCHAR2(30),
    mobile_number        VARCHAR2(30),
    emergency_contact    VARCHAR2(150),
    emergency_phone      VARCHAR2(30),
    hire_date            DATE NOT NULL,
    termination_date     DATE,
    employment_status    VARCHAR2(50),
    employment_type      VARCHAR2(50),
    probation_end_date   DATE,
    job_id               VARCHAR2(20),
    department_id        NUMBER,
    manager_id           NUMBER,
    salary               NUMBER(15,2),
    commission_pct       NUMBER(5,2),
    bonus_amount         NUMBER(15,2),
    stock_option_grant   NUMBER,
    bank_account_number  VARCHAR2(50),
    bank_name            VARCHAR2(100),
    tax_code             VARCHAR2(30),
    social_security_no   VARCHAR2(50),
    vacation_days        NUMBER,
    sick_leave_days      NUMBER,
    performance_score    NUMBER(5,2),
    last_promotion_date  DATE,
    last_salary_review   DATE,
    remote_worker_flag   CHAR(1) CHECK (remote_worker_flag IN ('Y','N')),
    background_check_flag CHAR(1) CHECK (background_check_flag IN ('Y','N')),
    active_flag          CHAR(1) DEFAULT 'Y' CHECK (active_flag IN ('Y','N')),
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP,
    created_by           VARCHAR2(50),
    updated_at           TIMESTAMP,
    updated_by           VARCHAR2(50),

    CONSTRAINT emp_job_fk
        FOREIGN KEY (job_id)
        REFERENCES jobs(job_id),

    CONSTRAINT emp_dept_fk
        FOREIGN KEY (department_id)
        REFERENCES departments(department_id),

    CONSTRAINT emp_manager_fk
        FOREIGN KEY (manager_id)
        REFERENCES employees(employee_id)
);

-- =========================
-- JOB HISTORY
-- =========================
CREATE TABLE job_history (
    history_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id          NUMBER,
    start_date           DATE NOT NULL,
    end_date             DATE,
    job_id               VARCHAR2(20),
    department_id        NUMBER,
    salary_at_time       NUMBER(15,2),
    manager_id           NUMBER,
    reason_for_change    VARCHAR2(200),
    performance_score    NUMBER(5,2),
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP,
    created_by           VARCHAR2(50),

    CONSTRAINT jh_employee_fk
        FOREIGN KEY (employee_id)
        REFERENCES employees(employee_id),

    CONSTRAINT jh_job_fk
        FOREIGN KEY (job_id)
        REFERENCES jobs(job_id),

    CONSTRAINT jh_dept_fk
        FOREIGN KEY (department_id)
        REFERENCES departments(department_id)
);