create FUNCTION          FNATPRLS0432 (PA_FIPAIS           IN NUMBER
                                                 ,PA_FICANAL          IN NUMBER
                                                 ,PA_FISUCURSAL       IN NUMBER
                                                 ,PA_FIFOLIO          IN NUMBER
                                                 ,PA_FIINTPAGADOS     IN NUMBER
                                                 ,PA_FCUSUARIOACTUAL  IN VARCHAR2 )

RETURN SYS_REFCURSOR
IS
   RCL_CURSALIDA1       SYS_REFCURSOR   := NULL;
   EXC_GENERAL          EXCEPTION;
   CSL_VALOR0           CONSTANT PLS_INTEGER   := 0;
   CSL_VALOR1           CONSTANT PLS_INTEGER   := 1;
   CSL_VALOR30          CONSTANT PLS_INTEGER   := 30;
   CSL_EXISN            CONSTANT VARCHAR2 (1)  := 'N';
   CSL_EXISS            CONSTANT VARCHAR2 (1)  := 'S';
   CSL_VAL0             CONSTANT VARCHAR2 (2)  := '0';
   CSL_00               CONSTANT VARCHAR2 (2)  := '00';
   CSL_01               CONSTANT VARCHAR2 (2)  := '01';
   CSL_ALTAOK           CONSTANT VARCHAR2 (50) := 'ALTA EFECTUADA EXITOSAMENTE';
   CSL_MODIOK           CONSTANT VARCHAR2 (50) := 'MODIFICACION EFECTUADA EXITOSAMENTE';
   CSL_ERRCON           CONSTANT VARCHAR2 (50) := 'DETALLE EN LA CONSULTA DEL CLIENTE';
   CSL_ERRFUN           CONSTANT VARCHAR2 (50) := 'DETALLE EN LA FUNCION DE MANTENIMIENTO';
   CSL_ERREXS           CONSTANT VARCHAR2 (50) := 'DETALLE POR QUE EL CLIENTE SI EXISTE';
   CSL_ERRINS           CONSTANT VARCHAR2 (50) := 'DETALLE EN EL ALTA DEL CLIENTE';
   CSL_ERRUPD           CONSTANT VARCHAR2 (50) := 'DETALLE EN LA MODIFICACION DEL CLIENTE';
   CSL_ERREXN           CONSTANT VARCHAR2 (50) := 'DETALLE POR QUE EL CLIENTE NO EXISTE';
   CSL_ERRENT           CONSTANT VARCHAR2 (50) := 'DETALLE POR DATOS DE ENTRADA';
   CSL_ERRUSR           CONSTANT VARCHAR2 (50) := 'DETALLE POR CODIGO USUARIO INVALIDO';
   CSL_USER             CONSTANT VARCHAR2 (50) := 'USRTAZ';
   CSL_NOMPROCESO       CONSTANT VARCHAR2 (50) := 'FNATPRLS0432';
   VL_ERRGEN            VARCHAR2 (50) := '';
   VL_FLAGEXIS          VARCHAR2 (1)  := 'N';
   VL_FINIVEL           RCREDITO.TANIVELCLIENTE.FINIVEL%TYPE            :=  0;
   VL_FCUSUARIOACT      RCREDITO.TANIVELCLIENTE.FCUSUARIOACTUALIZA%TYPE := '';

BEGIN

   IF (NVL(TRIM(PA_FIPAIS),CSL_VALOR0) = CSL_VALOR0 OR NVL(TRIM(PA_FICANAL),CSL_VALOR0) = CSL_VALOR0 OR
       NVL(TRIM(PA_FISUCURSAL),CSL_VALOR0) = CSL_VALOR0 OR NVL(TRIM(PA_FIFOLIO),CSL_VALOR0) = CSL_VALOR0) THEN

      VL_ERRGEN := CSL_ERRENT;
      RAISE EXC_GENERAL;
    END IF;

    IF  NVL(TRIM(PA_FCUSUARIOACTUAL),CSL_VAL0) = CSL_VAL0 THEN
        VL_ERRGEN := CSL_ERRUSR;
        RAISE EXC_GENERAL;
    END IF;
    VL_FCUSUARIOACT := SUBSTR(NVL(PA_FCUSUARIOACTUAL,CSL_USER), CSL_VALOR1, CSL_VALOR30);

   BEGIN
      SELECT FINIVEL
        INTO VL_FINIVEL
        FROM RCREDITO.TANIVELCLIENTE
       WHERE FIFOLIO    = PA_FIFOLIO
         AND FISUCURSAL = PA_FISUCURSAL
         AND FICANAL    = PA_FICANAL
         AND FIPAIS     = PA_FIPAIS;

      VL_FLAGEXIS := CSL_EXISS;

   EXCEPTION
        WHEN NO_DATA_FOUND THEN
             VL_FLAGEXIS := CSL_EXISN;
        WHEN TOO_MANY_ROWS THEN
             VL_FLAGEXIS := CSL_EXISS;
        WHEN OTHERS THEN
             USRATRZBAZ.SPREGISTRAERROR_ATRZ (SYSDATE, SQLCODE, SUBSTR (TRIM (SQLERRM), 1, 130) || '-' || CSL_ERRCON, CSL_NOMPROCESO);
             VL_ERRGEN := CSL_ERRCON;
             RAISE EXC_GENERAL;
   END;

   BEGIN
      SELECT FIIDNIVEL
        INTO VL_FINIVEL
        FROM RCREDITO.TANIVELINTERES
       WHERE FILIMITEINF <= PA_FIINTPAGADOS
         AND FILIMITESUP >= PA_FIINTPAGADOS
         AND ROWNUM = CSL_VALOR1;

   EXCEPTION
        WHEN NO_DATA_FOUND THEN
             VL_FINIVEL := CSL_VALOR0;
        WHEN TOO_MANY_ROWS THEN
             VL_FINIVEL := CSL_VALOR0;
        WHEN OTHERS THEN
             VL_FINIVEL := CSL_VALOR0;
   END;

   IF VL_FLAGEXIS = CSL_EXISN THEN
      BEGIN
          INSERT INTO RCREDITO.TANIVELCLIENTE (FIPAIS,FICANAL,FISUCURSAL,
                                               FIFOLIO,FIINTPAGADOS,FINIVEL,
                                               FDFECHAACTUAL,FDFECHAALTA,FCUSUARIOACTUALIZA,
                                               FDFECHAACTUALIZA )
                                       VALUES (PA_FIPAIS,PA_FICANAL,PA_FISUCURSAL,
                                               PA_FIFOLIO,PA_FIINTPAGADOS,VL_FINIVEL,
                                               SYSDATE,SYSDATE,VL_FCUSUARIOACT,
                                               SYSDATE );
          COMMIT;
          OPEN RCL_CURSALIDA1 FOR SELECT CSL_00 RESULTADO ,CSL_ALTAOK DETALLE
                                    FROM DUAL;
          RETURN RCL_CURSALIDA1;
      EXCEPTION
           WHEN DUP_VAL_ON_INDEX THEN
                ROLLBACK;
                VL_ERRGEN := CSL_ERREXS;
                RAISE EXC_GENERAL;
           WHEN OTHERS THEN
                ROLLBACK;
                USRATRZBAZ.SPREGISTRAERROR_ATRZ (SYSDATE, SQLCODE, SUBSTR (TRIM (SQLERRM), 1, 130) || '-' || CSL_ERRINS, CSL_NOMPROCESO);
                VL_ERRGEN := CSL_ERRINS;
                OPEN RCL_CURSALIDA1 FOR SELECT CSL_01 RESULTADO ,VL_ERRGEN DETALLE FROM DUAL;
                RETURN RCL_CURSALIDA1;
      END;
    ELSE
      BEGIN
         UPDATE RCREDITO.TANIVELCLIENTE
            SET FIINTPAGADOS       = PA_FIINTPAGADOS,
                FINIVEL            = VL_FINIVEL,
                FDFECHAACTUAL      = SYSDATE,
                FCUSUARIOACTUALIZA = VL_FCUSUARIOACT,
                FDFECHAACTUALIZA   = SYSDATE
          WHERE FIPAIS             = PA_FIPAIS
            AND FICANAL            = PA_FICANAL
            AND FISUCURSAL         = PA_FISUCURSAL
            AND FIFOLIO            = PA_FIFOLIO;

         IF SQL%FOUND THEN
            COMMIT;
            OPEN RCL_CURSALIDA1 FOR  SELECT CSL_00 RESULTADO ,CSL_MODIOK DETALLE
                                       FROM DUAL;
            RETURN RCL_CURSALIDA1;
         ELSE
            VL_ERRGEN := CSL_ERREXN;
         END IF;
      EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            USRATRZBAZ.SPREGISTRAERROR_ATRZ (SYSDATE, SQLCODE, SUBSTR (TRIM (SQLERRM), 1, 130) || '-' || CSL_ERRUPD, CSL_NOMPROCESO);
            VL_ERRGEN := CSL_ERRUPD;
            OPEN RCL_CURSALIDA1 FOR SELECT CSL_01 RESULTADO ,VL_ERRGEN DETALLE FROM DUAL;
            RETURN RCL_CURSALIDA1;
      END;
    END IF;

EXCEPTION
   WHEN EXC_GENERAL THEN
      OPEN RCL_CURSALIDA1 FOR
         SELECT CSL_01       RESULTADO
               ,VL_ERRGEN DETALLE
           FROM DUAL;
      RETURN RCL_CURSALIDA1;
   WHEN OTHERS THEN
      USRATRZBAZ.SPREGISTRAERROR_ATRZ (SYSDATE, SQLCODE, SUBSTR (TRIM (SQLERRM), 1, 130) || '-' || CSL_ERRFUN, CSL_NOMPROCESO);
      ROLLBACK;
      OPEN RCL_CURSALIDA1 FOR
         SELECT CSL_01       RESULTADO
               ,CSL_ERRFUN DETALLE
           FROM DUAL;
      RETURN RCL_CURSALIDA1;
END FNATPRLS0432;
/