CREATE OR REPLACE FUNCTION FNINGESTACDPCP(
    PA_IDPAIS IN NUMBER,
    PA_IDCANAL IN NUMBER,
    PA_IDSUCURSAL IN NUMBER,
    PA_IDFOLIO IN NUMBER,
    PA_STSID IN NUMBER,
    PA_BLOQUEOS IN VARCHAR2,
    PA_GESTPAISID IN NUMBER,
    PA_GESTCANALID IN NUMBER,
    PA_GESTSUCURSALID IN NUMBER,
    PA_PERPAGOID IN NUMBER,
    PA_PERPAGOSDIAS IN VARCHAR2,
    PA_CAPACIDADESPGO IN VARCHAR2
)
RETURN SYS_REFCURSOR
IS
    CSL_CODE_OK CONSTANT NUMBER := 0;
    CSL_CODE_ERR CONSTANT NUMBER := 1;
    CSL_MSG_OK CONSTANT VARCHAR2(300) := 'EXITO';
    CSL_MSG_NOT_FOUND CONSTANT VARCHAR2(20) := 'NOT_FOUND';
    CSL_MSG_PARAMS CONSTANT VARCHAR2(30) := 'PARAMETROS_INVALIDOS';
    CSL_MSG_STATUS CONSTANT VARCHAR2(30) := 'STATUS_INVALIDO';

    CUR_SALIDA SYS_REFCURSOR;
    VL_STSID_INTERNO NUMBER(1, 0);
    VL_FIDIAPAGOUNICO NUMBER(1, 0) := 0;
    VL_FILOCALIZACION NUMBER(1, 0) := 0;
    VL_FILISTANEGRA NUMBER(1, 0) := 0;
    VL_FIRMD NUMBER(1, 0) := 0;
    VL_FILEGAL NUMBER(1, 0) := 0;
    VL_FIDIFICILCOBRO NUMBER(1, 0) := 0;
    VL_FIPCJ NUMBER(1, 0) := 0;
    VL_MESSAGERR VARCHAR2(200);

    EXC_PARAMETROS_INVALIDOS EXCEPTION;
    EXC_STATUS_INVALIDO EXCEPTION;
    EXC_INFO_PREVIA_NO_ENCONTRADA EXCEPTION;
    EXC_BLOQUEOS_INVALIDOS EXCEPTION;
    EXC_DIAS_INVALIDOS EXCEPTION;
    EXC_CAPACIDADES_INVALIDAS EXCEPTION;

    PRAGMA EXCEPTION_INIT(EXC_INFO_PREVIA_NO_ENCONTRADA, -20504);
    PRAGMA EXCEPTION_INIT(EXC_BLOQUEOS_INVALIDOS, -20503);
    PRAGMA EXCEPTION_INIT(EXC_DIAS_INVALIDOS, -20506);
    PRAGMA EXCEPTION_INIT(EXC_CAPACIDADES_INVALIDAS, -20507);
BEGIN
    IF PA_IDPAIS IS NULL OR PA_IDCANAL IS NULL OR PA_IDSUCURSAL IS NULL OR PA_IDFOLIO IS NULL THEN
        RAISE EXC_PARAMETROS_INVALIDOS;
    END IF;

    IF PA_STSID IS NULL THEN
        RAISE EXC_STATUS_INVALIDO;
    END IF;

    CASE PA_STSID
        WHEN 0 THEN VL_STSID_INTERNO := 3;
        WHEN 1 THEN VL_STSID_INTERNO := 0;
        WHEN 2 THEN VL_STSID_INTERNO := 9;
        WHEN 3 THEN VL_STSID_INTERNO := 1;
        WHEN 4 THEN VL_STSID_INTERNO := 3;
        WHEN 5 THEN VL_STSID_INTERNO := 9;
        ELSE
            RAISE EXC_STATUS_INVALIDO;
    END CASE;

    SPINGESTASYNCBLOQUEOSCP(
        PA_IDPAIS => PA_IDPAIS,
        PA_IDCANAL => PA_IDCANAL,
        PA_IDSUCURSAL => PA_IDSUCURSAL,
        PA_IDFOLIO => PA_IDFOLIO,
        PA_STSID_EXTERNO => PA_STSID,
        PA_STSID_INTERNO => VL_STSID_INTERNO,
        PA_BLOQUEOS => PA_BLOQUEOS,
        PO_FIDIAPAGOUNICO => VL_FIDIAPAGOUNICO,
        PO_FILOCALIZACION => VL_FILOCALIZACION,
        PO_FILISTANEGRA => VL_FILISTANEGRA,
        PO_FIRMD => VL_FIRMD,
        PO_FILEGAL => VL_FILEGAL,
        PO_FIDIFICILCOBRO => VL_FIDIFICILCOBRO,
        PO_FIPCJ => VL_FIPCJ
    );

    SPINGESTALINEAGESTORACP(
        PA_IDPAIS => PA_IDPAIS,
        PA_IDCANAL => PA_IDCANAL,
        PA_IDSUCURSAL => PA_IDSUCURSAL,
        PA_IDFOLIO => PA_IDFOLIO,
        PA_STSID_EXTERNO => PA_STSID,
        PA_GESTPAISID => PA_GESTPAISID,
        PA_GESTCANALID => PA_GESTCANALID,
        PA_GESTSUCURSALID => PA_GESTSUCURSALID
    );

    IF PA_PERPAGOID IS NOT NULL THEN
        SPINGESTADIASPAGOCP(
            PA_IDPAIS => PA_IDPAIS,
            PA_IDCANAL => PA_IDCANAL,
            PA_IDSUCURSAL => PA_IDSUCURSAL,
            PA_IDFOLIO => PA_IDFOLIO,
            PA_STSID_EXTERNO => PA_STSID,
            PA_PERPAGOID => PA_PERPAGOID,
            PA_PERPAGOSDIAS => PA_PERPAGOSDIAS
        );
    END IF;

    IF PA_CAPACIDADESPGO IS NOT NULL THEN
        SPINGESTACAPACIDADESCP(
            PA_IDPAIS => PA_IDPAIS,
            PA_IDCANAL => PA_IDCANAL,
            PA_IDSUCURSAL => PA_IDSUCURSAL,
            PA_IDFOLIO => PA_IDFOLIO,
            PA_STSID_INTERNO => VL_STSID_INTERNO,
            PA_GESTCANALID => PA_GESTCANALID,
            PA_GESTSUCURSALID => PA_GESTSUCURSALID,
            PA_CAPACIDADESPGO => PA_CAPACIDADESPGO,
            PA_FIDIAPAGOUNICO => VL_FIDIAPAGOUNICO,
            PA_FILOCALIZACION => VL_FILOCALIZACION,
            PA_FILISTANEGRA => VL_FILISTANEGRA,
            PA_FIRMD => VL_FIRMD,
            PA_FILEGAL => VL_FILEGAL,
            PA_FIDIFICILCOBRO => VL_FIDIFICILCOBRO,
            PA_FIPCJ => VL_FIPCJ
        );
    END IF;

    COMMIT;

    OPEN CUR_SALIDA FOR
        SELECT CSL_CODE_OK CODIGO,
               CSL_MSG_OK MENSAJE
          FROM DUAL;

    RETURN CUR_SALIDA;
EXCEPTION
    WHEN EXC_PARAMETROS_INVALIDOS THEN
        ROLLBACK;

        OPEN CUR_SALIDA FOR
            SELECT CSL_CODE_ERR CODIGO,
                   CSL_MSG_PARAMS MENSAJE
              FROM DUAL;

        RETURN CUR_SALIDA;
    WHEN EXC_STATUS_INVALIDO THEN
        ROLLBACK;

        OPEN CUR_SALIDA FOR
            SELECT CSL_CODE_ERR CODIGO,
                   CSL_MSG_STATUS MENSAJE
              FROM DUAL;

        RETURN CUR_SALIDA;
    WHEN EXC_INFO_PREVIA_NO_ENCONTRADA THEN
        ROLLBACK;

        OPEN CUR_SALIDA FOR
            SELECT CSL_CODE_ERR CODIGO,
                   CSL_MSG_NOT_FOUND MENSAJE
              FROM DUAL;

        RETURN CUR_SALIDA;
    WHEN EXC_BLOQUEOS_INVALIDOS THEN
        ROLLBACK;

        OPEN CUR_SALIDA FOR
            SELECT CSL_CODE_ERR CODIGO,
                   'FORMATO_INVALIDO_BLOQUEOS' MENSAJE
              FROM DUAL;

        RETURN CUR_SALIDA;
    WHEN EXC_DIAS_INVALIDOS THEN
        ROLLBACK;

        OPEN CUR_SALIDA FOR
            SELECT CSL_CODE_ERR CODIGO,
                   'FORMATO_INVALIDO_DIAS_PAGO' MENSAJE
              FROM DUAL;

        RETURN CUR_SALIDA;
    WHEN EXC_CAPACIDADES_INVALIDAS THEN
        ROLLBACK;

        OPEN CUR_SALIDA FOR
            SELECT CSL_CODE_ERR CODIGO,
                   'FORMATO_INVALIDO_CAPACIDADES' MENSAJE
              FROM DUAL;

        RETURN CUR_SALIDA;
    WHEN OTHERS THEN
        ROLLBACK;
        VL_MESSAGERR := SUBSTR(SQLERRM || ' - ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, 1, 200);

        OPEN CUR_SALIDA FOR
            SELECT CSL_CODE_ERR CODIGO,
                   VL_MESSAGERR MENSAJE
              FROM DUAL;

        RETURN CUR_SALIDA;
END FNINGESTACDPCP;
/

