whenever sqlerror exit failure rollback

define RCREDITO_PASSWORD = RCREDITO_123
define USRATRZBAZ_PASSWORD = USRATRZBAZ_123

CREATE USER RCREDITO IDENTIFIED BY "&RCREDITO_PASSWORD"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO RCREDITO;
GRANT CREATE TABLE TO RCREDITO;
GRANT CREATE PROCEDURE TO RCREDITO;
GRANT CREATE SEQUENCE TO RCREDITO;
GRANT CREATE VIEW TO RCREDITO;
GRANT CREATE SYNONYM TO RCREDITO;
GRANT CREATE TYPE TO RCREDITO;
GRANT CREATE TRIGGER TO RCREDITO;

CREATE USER USRATRZBAZ IDENTIFIED BY "&USRATRZBAZ_PASSWORD"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO USRATRZBAZ;
GRANT CREATE PROCEDURE TO USRATRZBAZ;
GRANT CREATE TABLE TO USRATRZBAZ;

ALTER USER RCREDITO ACCOUNT UNLOCK;
ALTER USER USRATRZBAZ ACCOUNT UNLOCK;