whenever sqlerror exit failure rollback

CREATE TABLE USRATRZBAZ.ATRZ_ERROR_LOG (
    FDREGISTRO DATE,
    FICODIGO NUMBER,
    FCMENSAJE VARCHAR2(4000),
    FCPROCESO VARCHAR2(200)
);

CREATE OR REPLACE PROCEDURE USRATRZBAZ.SPREGISTRAERROR_ATRZ (
    PA_FECHA IN DATE,
    PA_CODIGO IN NUMBER,
    PA_MENSAJE IN VARCHAR2,
    PA_PROCESO IN VARCHAR2
)
IS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO USRATRZBAZ.ATRZ_ERROR_LOG (
        FDREGISTRO,
        FICODIGO,
        FCMENSAJE,
        FCPROCESO
    )
    VALUES (
        PA_FECHA,
        PA_CODIGO,
        SUBSTR(PA_MENSAJE, 1, 4000),
        SUBSTR(PA_PROCESO, 1, 200)
    );

    COMMIT;
END SPREGISTRAERROR_ATRZ;
/

GRANT EXECUTE ON USRATRZBAZ.SPREGISTRAERROR_ATRZ TO RCREDITO;

CREATE TABLE RCREDITO.TACRBITCAMBIOSLCR (
    FIPAIS NUMBER,
    FICANAL NUMBER,
    FISUCURSAL NUMBER,
    FIFOLIO NUMBER,
    FIIDBLOQUEO NUMBER,
    FIIDSTATUS NUMBER,
    FDPROCESO DATE,
    FISTATCRED NUMBER,
    FISTATCEN NUMBER,
    FINOPEDIDO NUMBER,
    FCEMPLEADO VARCHAR2(100),
    FCPUESTO VARCHAR2(100),
    FITRANNO NUMBER,
    FCTRANWS VARCHAR2(100),
    FCTRANUSR VARCHAR2(100),
    FCAPLICACION VARCHAR2(100)
);

CREATE TABLE RCREDITO.CENCLIENTETIENDA (
    FIPAIS NUMBER,
    FICANAL NUMBER,
    FISUCURSAL NUMBER,
    FIFOLIO NUMBER,
    FINGCIOID NUMBER(5,0),
    FINOTIENDA NUMBER(5,0),
    FICTEID NUMBER(10,0),
    FIDIGITOVER NUMBER(5,0),
    FDFECHA DATE
);

CREATE TABLE RCREDITO.CENLINEADECREDITO (
    FIPAIS NUMBER,
    FICANAL NUMBER,
    FISUCURSAL NUMBER,
    FIFOLIO NUMBER,
    FIPAISGESTOR NUMBER,
    FICANALGESTOR NUMBER,
    FISUCURSALGESTORA NUMBER,
    FISTATUS NUMBER,
    FDFECHAALTA DATE,
    FDFECHAACT DATE,
    FINGCIOID NUMBER(5,0),
    FINOTIENDA NUMBER(5,0),
    FICTEID NUMBER(10,0),
    FIDIGITOVER NUMBER(5,0),
    FISTSCU NUMBER,
    CONSTRAINT PK_CENLINEADECREDITO PRIMARY KEY (FIPAIS, FICANAL, FISUCURSAL, FIFOLIO)
);

CREATE TABLE RCREDITO.TARCLLINFOCUENTACLIENTE (
    FIPAIS NUMBER,
    FICANAL NUMBER,
    FISUCURSAL NUMBER,
    FIFOLIO NUMBER,
    FCTARJETA VARCHAR2(50),
    FIPLAZO NUMBER,
    FIDIAPAGO NUMBER,
    FNCAPACIDADPAGO NUMBER(15,2),
    FCCORREO VARCHAR2(250),
    FCNOCELULAR VARCHAR2(50),
    FDFECHA DATE,
    CONSTRAINT PK_TARCLLINFOCUENTACLIENTE PRIMARY KEY (FIPAIS, FICANAL, FISUCURSAL, FIFOLIO)
);

CREATE TABLE RCREDITO.TADIAPAGOQM (
    FIPAIS NUMBER,
    FICANAL NUMBER,
    FISUCURSAL NUMBER,
    FIFOLIO NUMBER,
    FNPERIODO NUMBER,
    FNDIAQ1 NUMBER,
    FNDIAQ2 NUMBER,
    FNDIAM NUMBER,
    FDFECHAREG DATE,
    FISTATUS NUMBER,
    FCUSUARIOACTUALIZA VARCHAR2(50),
    FDFECHAACTUALIZA DATE,
    FITIPOPAGOID NUMBER,
    FIDIAS VARCHAR2(100),
    CONSTRAINT PK_TADIAPAGOQM PRIMARY KEY (FIPAIS, FICANAL, FISUCURSAL, FIFOLIO)
);

CREATE TABLE RCREDITO.CREDLINEADECREDITO (
    FIPAIS NUMBER,
    FICANAL NUMBER,
    FISUCURSAL NUMBER,
    FIFOLIO NUMBER,
    FNCAPACIDADPAGO NUMBER(15,2),
    FNCAPACIDADPAGODISP NUMBER(15,2),
    FNMONTOLCR NUMBER(15,2),
    FIPLAZOMAX NUMBER,
    FNENGANCHE1COMPRA NUMBER(15,2),
    FIDIAPAGOUNICO NUMBER,
    FISTATUSAUTORIZACION NUMBER,
    FDFECHAULTACT DATE,
    FDFECHAULTAUT DATE,
    FISTATUS NUMBER,
    FITRANNO NUMBER,
    FILISTANEGRA NUMBER,
    FILOCALIZACION NUMBER,
    FIRMD NUMBER,
    FILEGAL NUMBER,
    FIDIFICILCOBRO NUMBER,
    FIACEPTAPP NUMBER,
    FNSUMSALDO NUMBER(15,2),
    FICOMPRAS NUMBER,
    FDFECHAALTACREDITO DATE,
    FIPCJ NUMBER,
    CONSTRAINT PK_CREDLINEADECREDITO PRIMARY KEY (FIPAIS, FICANAL, FISUCURSAL, FIFOLIO)
);

CREATE TABLE RCREDITO.TACRCAPMAXPROD (
    FIPAIS NUMBER,
    FICANAL NUMBER,
    FISUCURSAL NUMBER,
    FIFOLIO NUMBER,
    FIORIGENID NUMBER,
    FICAPACIDAD NUMBER(15,2),
    FIESACTIVA NUMBER,
    FITRANO NUMBER,
    FICANALTRANO NUMBER,
    FISUCURSALTRANO NUMBER,
    FDULTIMA_MODIFICACION DATE,
    FCUSUARIO_MODIFICO VARCHAR2(100),
    CONSTRAINT PK_TACRCAPMAXPROD PRIMARY KEY (FIPAIS, FICANAL, FISUCURSAL, FIFOLIO, FIORIGENID)
);

CREATE TABLE RCREDITO.TABNPLHEADER (
    FCTIPOMENSAJE VARCHAR2(100),
    FIPAISCTE NUMBER,
    FICANALCTE NUMBER,
    FISUCURSALCTE NUMBER,
    FIFOLIOCTE NUMBER,
    FCCODFECHA VARCHAR2(50),
    FCPLATFORMID VARCHAR2(100),
    FCSUBPLATFORMID VARCHAR2(100),
    FCSICU VARCHAR2(100),
    FIPAISHEAD NUMBER,
    FICANALHEAD NUMBER,
    FISUCURSALHEAD NUMBER,
    FDFECHAMOVIMEINTO DATE,
    FCIP VARCHAR2(100),
    FCUSER VARCHAR2(100),
    FCCOMERNAME VARCHAR2(200),
    FCCOMERAFIL VARCHAR2(200),
    FCCOMERGIRO VARCHAR2(200),
    FCCOMERSKU VARCHAR2(200),
    FCTARJETA VARCHAR2(50),
    FIOFERID NUMBER,
    FIOFERPLAZO NUMBER,
    FIOFERMONTO NUMBER,
    FIOFERINTERES NUMBER,
    FIOFERABONOP NUMBER,
    FIOFERABONON NUMBER,
    FIOFERABONOD NUMBER,
    FDFECHAACTUALIZA DATE,
    FCUSUARIOACTUALIZA VARCHAR2(100),
    CONSTRAINT PK_TABNPLHEADER PRIMARY KEY (FCTIPOMENSAJE, FIPAISCTE, FICANALCTE, FISUCURSALCTE, FIFOLIOCTE, FCCODFECHA)
);

CREATE TABLE RCREDITO.TABNPLDETAIL (
    FCTIPOMENSAJE VARCHAR2(100),
    FIPAISCTE NUMBER,
    FICANALCTE NUMBER,
    FISUCURSALCTE NUMBER,
    FIFOLIOCTE NUMBER,
    FCCODFECHA VARCHAR2(50),
    FCDEPCUENTA VARCHAR2(100),
    FCDEPCODIGO VARCHAR2(100),
    FCDEPDIVISA VARCHAR2(100),
    FIDEPMONTO NUMBER,
    FCDEPFOLIO VARCHAR2(100),
    FCDEPREFERENCIA VARCHAR2(100),
    FCDEPOBS VARCHAR2(1000),
    FDDEPFECHA DATE,
    FCDEPLATITUD VARCHAR2(100),
    FCDEPLONGITUD VARCHAR2(100),
    FCDOCEMP VARCHAR2(100),
    FCDOCTELEMISOR VARCHAR2(100),
    FCDOCTELRECEPTOR VARCHAR2(100),
    FCDOCNOMBRE VARCHAR2(100),
    FCDOCAPELLIDOP VARCHAR2(100),
    FCDOCAPELLIDOM VARCHAR2(100),
    FCAUTORIZACION VARCHAR2(100),
    FIPEDPAIS NUMBER,
    FIPEDCANAL NUMBER,
    FIPEDSUCURSAL NUMBER,
    FIPEDPEDIDO NUMBER,
    FIIDBLOQC NUMBER,
    FIIDBLOQD NUMBER,
    FIIDBLOQE NUMBER,
    FCRUTATICKET VARCHAR2(500),
    FCRUTAAMORT VARCHAR2(500),
    FICAT NUMBER,
    FCRESPCOBRANZA VARCHAR2(500),
    FCDESCRESPCOBRANZA VARCHAR2(500),
    FDFECHAACTUALIZA DATE,
    FCUSUARIOACTUALIZA VARCHAR2(100),
    CONSTRAINT PK_TABNPLDETAIL PRIMARY KEY (FCTIPOMENSAJE, FIPAISCTE, FICANALCTE, FISUCURSALCTE, FIFOLIOCTE, FCCODFECHA)
);

CREATE TABLE RCREDITO.TANIVELCLIENTE (
    FIPAIS NUMBER,
    FICANAL NUMBER,
    FISUCURSAL NUMBER,
    FIFOLIO NUMBER,
    FIINTPAGADOS NUMBER,
    FINIVEL NUMBER,
    FDFECHAACTUAL DATE,
    FDFECHAALTA DATE,
    FCUSUARIOACTUALIZA VARCHAR2(50),
    FDFECHAACTUALIZA DATE,
    CONSTRAINT PK_TANIVELCLIENTE PRIMARY KEY (FIPAIS, FICANAL, FISUCURSAL, FIFOLIO)
);

CREATE TABLE RCREDITO.TANIVELINTERES (
    FIIDNIVEL NUMBER PRIMARY KEY,
    FILIMITEINF NUMBER,
    FILIMITESUP NUMBER
);