whenever sqlerror exit failure rollback

INSERT INTO RCREDITO.CENCLIENTETIENDA (
    FIPAIS,
    FICANAL,
    FISUCURSAL,
    FIFOLIO,
    FINGCIOID,
    FINOTIENDA,
    FICTEID,
    FIDIGITOVER,
    FDFECHA
)
VALUES (1, 1, 10, 1001, 101, 501, 9001, 7, SYSDATE);

INSERT INTO RCREDITO.CENCLIENTETIENDA (
    FIPAIS,
    FICANAL,
    FISUCURSAL,
    FIFOLIO,
    FINGCIOID,
    FINOTIENDA,
    FICTEID,
    FIDIGITOVER,
    FDFECHA
)
VALUES (1, 1, 10, 1002, 102, 502, 9002, 8, SYSDATE);

INSERT INTO RCREDITO.TANIVELINTERES (FIIDNIVEL, FILIMITEINF, FILIMITESUP) VALUES (1, 0, 30);
INSERT INTO RCREDITO.TANIVELINTERES (FIIDNIVEL, FILIMITEINF, FILIMITESUP) VALUES (2, 31, 60);
INSERT INTO RCREDITO.TANIVELINTERES (FIIDNIVEL, FILIMITEINF, FILIMITESUP) VALUES (3, 61, 9999);

INSERT INTO RCREDITO.TACRBITCAMBIOSLCR (
    FIPAIS,
    FICANAL,
    FISUCURSAL,
    FIFOLIO,
    FIIDBLOQUEO,
    FIIDSTATUS,
    FDPROCESO,
    FISTATCRED,
    FISTATCEN,
    FINOPEDIDO,
    FCEMPLEADO,
    FCPUESTO,
    FITRANNO,
    FCTRANWS,
    FCTRANUSR,
    FCAPLICACION
)
VALUES (1, 1, 10, 1002, 117, 1, SYSDATE - 1, 0, 0, 0, USER, 'SYS', 0, 'SERVER', USER, 'SERVER');

INSERT INTO RCREDITO.TACRBITCAMBIOSLCR (
    FIPAIS,
    FICANAL,
    FISUCURSAL,
    FIFOLIO,
    FIIDBLOQUEO,
    FIIDSTATUS,
    FDPROCESO,
    FISTATCRED,
    FISTATCEN,
    FINOPEDIDO,
    FCEMPLEADO,
    FCPUESTO,
    FITRANNO,
    FCTRANWS,
    FCTRANUSR,
    FCAPLICACION
)
VALUES (1, 1, 10, 1002, 115, 0, SYSDATE - 1, 0, 0, 0, USER, 'SYS', 0, 'SERVER', USER, 'SERVER');

COMMIT;