whenever sqlerror exit failure rollback

ALTER SESSION SET CURRENT_SCHEMA = RCREDITO;

@../procedures/SPINGESTASYNCBLOQUEOSCP.sql
@../procedures/SPINGESTALINEAGESTORACP.sql
@../procedures/SPINGESTADIASPAGOCP.sql
@../procedures/SPINGESTACAPACIDADESCP.sql
@../fuctions/FNINGESTACDPCP.sql
@../procedures/SPBITACORABNPL.sql
@../fuctions/FNATPRLS0432.sql

SHOW ERRORS PROCEDURE SPINGESTASYNCBLOQUEOSCP
SHOW ERRORS PROCEDURE SPINGESTALINEAGESTORACP
SHOW ERRORS PROCEDURE SPINGESTADIASPAGOCP
SHOW ERRORS PROCEDURE SPINGESTACAPACIDADESCP
SHOW ERRORS FUNCTION FNINGESTACDPCP
SHOW ERRORS PROCEDURE SPBITACORABNPL
SHOW ERRORS FUNCTION FNATPRLS0432