whenever sqlerror exit failure rollback

ALTER SESSION SET CURRENT_SCHEMA = RCREDITO;

@../fuctions/FNINGESTACDPCP.sql
@../procedures/SPBITACORABNPL.sql
@../fuctions/FNATPRLS0432.sql

SHOW ERRORS FUNCTION FNINGESTACDPCP
SHOW ERRORS PROCEDURE SPBITACORABNPL
SHOW ERRORS FUNCTION FNATPRLS0432