whenever sqlerror exit failure rollback

define TEST_USER = SYS

GRANT EXECUTE ON RCREDITO.SPINGESTASYNCBLOQUEOSCP TO &TEST_USER;
GRANT EXECUTE ON RCREDITO.SPINGESTALINEAGESTORACP TO &TEST_USER;
GRANT EXECUTE ON RCREDITO.SPINGESTADIASPAGOCP TO &TEST_USER;
GRANT EXECUTE ON RCREDITO.SPINGESTACAPACIDADESCP TO &TEST_USER;
GRANT EXECUTE ON RCREDITO.FNINGESTACDPCP TO &TEST_USER;
GRANT EXECUTE ON RCREDITO.SPBITACORABNPL TO &TEST_USER;
GRANT EXECUTE ON RCREDITO.FNATPRLS0432 TO &TEST_USER;

GRANT SELECT, INSERT, UPDATE, DELETE ON RCREDITO.TACRBITCAMBIOSLCR TO &TEST_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON RCREDITO.CENCLIENTETIENDA TO &TEST_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON RCREDITO.CENLINEADECREDITO TO &TEST_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON RCREDITO.TARCLLINFOCUENTACLIENTE TO &TEST_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON RCREDITO.TADIAPAGOQM TO &TEST_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON RCREDITO.CREDLINEADECREDITO TO &TEST_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON RCREDITO.TACRCAPMAXPROD TO &TEST_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON RCREDITO.TABNPLHEADER TO &TEST_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON RCREDITO.TABNPLDETAIL TO &TEST_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON RCREDITO.TANIVELCLIENTE TO &TEST_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON RCREDITO.TANIVELINTERES TO &TEST_USER;

GRANT SELECT ON USRATRZBAZ.ATRZ_ERROR_LOG TO &TEST_USER;
GRANT EXECUTE ON USRATRZBAZ.SPREGISTRAERROR_ATRZ TO &TEST_USER;